Added Pangolin Connector
pangolindex/dsa-connectors pull request #1
Opened 2021-10-19 22:34 UTC by prodesert22

2021-10-20 09:36 UTC, benber86 commented on contracts/avalanche/connectors/pangolin/main.sol
> +    function buy(
Does DSA offer buys/sales ?

2021-10-20 09:36 UTC, benber86 requested changes
Nice, could you add tests?

2021-10-20 13:11 UTC, prodesert22 commented on contracts/avalanche/connectors/pangolin/main.sol
> +    function buy(
I believe it's for swap
https://docs.instadapp.io/connectors/mainnet/uniswap#buy

2021-10-20 13:11 UTC, prodesert22 commented
> Nice, could you add tests?

Ok, I'll add

2021-10-28 23:33 UTC, benber86 approved these changes
lgtm

2021-11-02 15:43 UTC, merged